language: ruby
addons:
  apt:
    packages:
      - nodejs
      - libgd2-xpm-dev
rvm:
  - 2.2.2
  - rbx-2.1.1
script: 
  - cp config/database.yml.example config/database.yml
  - rake db:migrate
  - rake test