#!/bin/bash

RAILS_S_ROOT_DIR=/home/osuser/TDef_Web

#export RAILS_WEBSERV=thin
#export MEMSTORE_SIZE=384 

function rails() {
  if [ "$1" = "start" ]; then
     rails server -d -e "production"
     return 0
  elif [ "$1" = "stop" ]; then
     if [ -f tmp/pids/server.pid ]; then
        kill $2 $(cat tmp/pids/server.pid)
	rm tmp/pids/server.pid
        return 0
     else
        echo "It seems there is no server running"
        return 1
     fi
  elif [ "$1" = "restart" ]; then
     rails stop && rails start $2
  else
     command rails $@
  fi;
}


cd $RAILS_S_ROOT_DIR
rails $1 $2