#!/bin/bash

RAILS_S_ROOT_DIR=/home/osuser/TDef_Web

RAILS_PID=/tmp/rails_server.pid

export RAILS_ENV=production
#export RAILS_WEBSERV=thin
#export MEMSTORE_SIZE=384 
#+ 64 mb used for assets caching

function rails() {
  if [ "$1" = "start" ]; then
     bundle exec rails server -d -e "production" --pid=$RAILS_PID
     return 0
  elif [ "$1" = "stop" ]; then
     if [ -f $RAILS_PID ]; then
        kill $2 $(cat $RAILS_PID)
	rm $RAILS_PID
        return 0
     else
        echo "It seems there is no server running"
        return 1
     fi
  elif [ "$1" = "restart" ]; then
     rails stop 
     rails start $2
 elif [ "$1" = "update" ]; then
     bash update.sh
  else
     bundle exec rails $@
  fi;
}


cd $RAILS_S_ROOT_DIR
rails $1 $2