#!/bin/bash

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
#rvm use ruby-railsexpress

RAILS_S_ROOT_DIR=/home/osuser/TDef_Web

RAILS_PID=/tmp/rails_server.pid

export RAILS_ENV=production
export RUBY_GC_HEAP_FREE_SLOTS=200000
export RUBY_GC_MALLOC_LIMIT=60000000

#export RAILS_WEBSERV=thin
#export MEMSTORE_SIZE=384 
#export USE_OJ=true 

export UPDATE_DB=0 
export COMPILE_ASSETS=0 

CHILD_NODES=""

function child_nodes(){
	for i in $CHILD_NODES; do
		ssh osuser@$i rails_server $1
	done
}

function rails() {
  if [ "$1" = "start" ]; then
     bundle exec rails server -d --pid=$RAILS_PID
     return 0
  elif [ "$1" = "stop" ]; then
     if [ -f $RAILS_PID ]; then
        kill $2 $(cat $RAILS_PID)
	rm $RAILS_PID
	echo "server stopped"
#        return 0
     else
        echo "It seems there is no server running"
#        return 1
     fi
     child_nodes stop
     return 0
  elif [ "$1" = "restart" ]; then
     rails stop 
     rails start $2
 elif [ "$1" = "update" ]; then
     rails stop
     bash update.sh
     child_nodes update
  else
     bundle exec rails $@
  fi;
}


cd $RAILS_S_ROOT_DIR
rails $1 $2